version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/commerspace
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/commerspace/
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres' ]
      retries: 3
      timeout: 5s

volumes:
  postgres-data:
